---
- name: Find out stuff
  hosts: all
  connection: local
  tasks:
  - name: Find hostname
    setup:
     filter: "*hostname*"
  - name: Find the IPv4 Address
    debug: var=ansible_default_ipv4 
  - name: Copy a file
    copy:
      content: "The content of the file"
      dest: "/tmp/"
      src: "/home/mandla/file2.txt"
